apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vulboard.fullname" . }}-secret
  namespace: default
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=       # Example: "password"
  RABBITMQ_PASSWORD: c2VjcmV0cGFzcw==   # Example: "secretpass"
