apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vulboard.fullname" . }}
  labels:
    {{- include "vulboard.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: vulboard
      app.kubernetes.io/name: vulboard
  endpoints:
    - port: http
      interval: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
